language: python
cache:
  - pip
sudo: required
# see https://github.com/travis-ci/travis-ci/issues/8647
os:
- linux
branches:
  only:
  - master
install:
  - |
    sudo pip install -q tox-travis virtualenv | cat
    ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa
    cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
    echo "  StrictHostKeyChecking no" >> ~/.ssh/config
    chmod g-rw,o-rw ~/.ssh/*
stages:
  - lint
  - test
  - deploy
jobs:
  include:
    - stage: lint
      script:
      - pip install -q tox | cat
      - tox -e lint
      install: skip
    - stage: test
      script: make info test dist
      python: 2.7
      env: TOXENV=py27
    - stage: test
      script: make info test dist
      python: 3.4
      env: TOXENV=py34
    - stage: test
      script: make info test dist
      python: 3.5
      env: TOXENV=py35
    - stage: test
      script: make info test dist
      python: 3.6
      env: TOXENV=py36 PYTHON='3.6' PYENV_VERSION='system'
    - stage: deploy
      script: make dist
